appaimage:
  - Visual Studio 2017
clone_folder: c:\projects\source
skip_non_tags: true
platform:
  - x64
install:
  - cmd: echo "Downloading conan..."
  - cmd: set PATH=%PATH%;%PYTHON%/Scripts/
  - cmd: pip.exe install conan
  - cmd: conan user # Create the conan data directory
  - cmd: conan --version
build_script:
  - cmd: mkdir build
  - cmd: cd build
  - cmd: cmake c:\projects\source -G "Visual Studio 15"
  - cmd: cmake --build . --config Release
test_script:
  - cmd: cd bin
  - cmd: UnitTest.exe
artifacts:
  path: build\Release\*.exe
  name: binary_executable