version: 1.0.{build}
image:
  - Visual Studio 2017
configuration:
  - Release
clone_folder: c:\projects\source
skip_non_tags: true
platform:
  - x64

install:
  - cmd: echo "Downloading conan..."
  - cmd: set PATH=%PATH%;%PYTHON%/Scripts/
  - cmd: python --version
  - cmd: pip.exe install conan
  - cmd: conan user # Create the conan data directory
  - cmd: conan --version

before_build:
  - cmd: mkdir build
  - cmd: cd build
  - cmd: conan remote add bincrafters "https://api.bintray.com/conan/bincrafters/public-conan"
  - cmd: conan install .. --build=missing
  - cmd: echo "conan installation success!"
  - cmd: cmake c:\projects\source -G "Visual Studio 15"

build_script:
  - cmd: cmake --build . --config %CONFIGURATION%
  - cmd: ctest -C %CONFIGURATION%

artifacts:
  path: build\%CONFIGURATION%\*.exe
  name: binary_executable
